
services:
  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - postgres-db
    restart: always
    container_name: smarthome-app
    environment:
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/smarthome
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smarthome
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
